---
name: Devel-throttle
version: 0.01
author:
  - |-
    Copyright (C) 2009, Guido Flohr E<lt>guido@imperia.netE<gt>, all
    rights reserved.
abstract: Slow down execution of Perl scripts
license: unknown
provides:
  DB:
    file: lib/Devel/throttle.pm
  Devel::throttle:
    file: lib/Devel/throttle.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
